const mongoose = require('mongoose');

// Create Schema
const TimetableSchema = new mongoose.Schema({
        classroomname:String,
    subject1:String,
    subject2:String,
    subject3:String,
    subject4:String,
    subject5:String,
    subject6:String,
    subject7:String,
    subject8:String,
    subject9:String,
    subject10:String,
    subject11:String,
    subject12:String,
    subject13:String,
    subject14:String,
    subject15:String,
    subject16:String,
    subject17:String,
    subject18:String,
    subject19:String,
    subject20:String,
    subject21:String,
    subject22:String,
    subject23:String,
    subject24:String,
    subject25:String,
    type1:Number,
    type2:Number,
    type3:Number,
    type4:Number,
    type5:Number,
    type6:Number,
    type7:Number,
    type8:Number,
    type9:Number,
    type10:Number,
    type11:Number,
    type12:Number,
    type13:Number,
    type14:Number,
    type15:Number,
    type16:Number,
    type17:Number,
    type18:Number,
    type19:Number,
    type20:Number,
    type21:Number,
    type22:Number,
    type23:Number,
    type24:Number,
    type25:Number,
})

const Timetable = mongoose.model('Timetable', TimetableSchema);

module.exports =  Timetable;